# a.out: main.o byte_buffer2.o
#     gcc -o app.out main.o foo.o
 
# main.o: byte_buffer2.hpp main.cpp
#     gcc -c -o main.o main.c
 
# foo.o: foo.h foo.c
#     gcc -c -o foo.o foo.c
 
# bar.o: bar.h bar.c
#     gcc -c -o bar.o bar.c